<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseAssignmentsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('course_assignments')->insert([
            [
                'course_assignment_id' => 1,
                'curricula_program_id' => 1,
                'semester_id' => 7,
                'course_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 2,
                'curricula_program_id' => 1,
                'semester_id' => 7,
                'course_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 3,
                'curricula_program_id' => 1,
                'semester_id' => 7,
                'course_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 4,
                'curricula_program_id' => 1,
                'semester_id' => 8,
                'course_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 5,
                'curricula_program_id' => 1,
                'semester_id' => 8,
                'course_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 6,
                'curricula_program_id' => 1,
                'semester_id' => 8,
                'course_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 7,
                'curricula_program_id' => 1,
                'semester_id' => 9,
                'course_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 8,
                'curricula_program_id' => 1,
                'semester_id' => 9,
                'course_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 9,
                'curricula_program_id' => 1,
                'semester_id' => 9,
                'course_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 40,
                'curricula_program_id' => 1,
                'semester_id' => 10,
                'course_id' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 41,
                'curricula_program_id' => 1,
                'semester_id' => 10,
                'course_id' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 42,
                'curricula_program_id' => 1,
                'semester_id' => 10,
                'course_id' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 19,
                'curricula_program_id' => 2,
                'semester_id' => 19,
                'course_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 20,
                'curricula_program_id' => 2,
                'semester_id' => 19,
                'course_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 21,
                'curricula_program_id' => 2,
                'semester_id' => 19,
                'course_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 22,
                'curricula_program_id' => 2,
                'semester_id' => 20,
                'course_id' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 23,
                'curricula_program_id' => 2,
                'semester_id' => 20,
                'course_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 24,
                'curricula_program_id' => 2,
                'semester_id' => 20,
                'course_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 25,
                'curricula_program_id' => 2,
                'semester_id' => 21,
                'course_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 26,
                'curricula_program_id' => 2,
                'semester_id' => 21,
                'course_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 27,
                'curricula_program_id' => 2,
                'semester_id' => 21,
                'course_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 43,
                'curricula_program_id' => 2,
                'semester_id' => 22,
                'course_id' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 44,
                'curricula_program_id' => 2,
                'semester_id' => 22,
                'course_id' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 45,
                'curricula_program_id' => 2,
                'semester_id' => 22,
                'course_id' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 10,
                'curricula_program_id' => 3,
                'semester_id' => 1,
                'course_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 11,
                'curricula_program_id' => 3,
                'semester_id' => 1,
                'course_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 12,
                'curricula_program_id' => 3,
                'semester_id' => 1,
                'course_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 13,
                'curricula_program_id' => 3,
                'semester_id' => 2,
                'course_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 14,
                'curricula_program_id' => 3,
                'semester_id' => 2,
                'course_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 15,
                'curricula_program_id' => 3,
                'semester_id' => 2,
                'course_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 16,
                'curricula_program_id' => 3,
                'semester_id' => 3,
                'course_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 17,
                'curricula_program_id' => 3,
                'semester_id' => 3,
                'course_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 18,
                'curricula_program_id' => 3,
                'semester_id' => 3,
                'course_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 28,
                'curricula_program_id' => 4,
                'semester_id' => 13,
                'course_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 29,
                'curricula_program_id' => 4,
                'semester_id' => 13,
                'course_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 30,
                'curricula_program_id' => 4,
                'semester_id' => 13,
                'course_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 31,
                'curricula_program_id' => 4,
                'semester_id' => 14,
                'course_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 32,
                'curricula_program_id' => 4,
                'semester_id' => 14,
                'course_id' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 33,
                'curricula_program_id' => 4,
                'semester_id' => 14,
                'course_id' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 34,
                'curricula_program_id' => 4,
                'semester_id' => 15,
                'course_id' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 35,
                'curricula_program_id' => 4,
                'semester_id' => 15,
                'course_id' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 36,
                'curricula_program_id' => 4,
                'semester_id' => 15,
                'course_id' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 37,
                'curricula_program_id' => 4,
                'semester_id' => 13,
                'course_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 38,
                'curricula_program_id' => 4,
                'semester_id' => 13,
                'course_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 39,
                'curricula_program_id' => 4,
                'semester_id' => 13,
                'course_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 47,
                'curricula_program_id' => 3,
                'semester_id' => 4,
                'course_id' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 48,
                'curricula_program_id' => 3,
                'semester_id' => 4,
                'course_id' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 49,
                'curricula_program_id' => 3,
                'semester_id' => 5,
                'course_id' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 50,
                'curricula_program_id' => 4,
                'semester_id' => 16,
                'course_id' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 51,
                'curricula_program_id' => 4,
                'semester_id' => 17,
                'course_id' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_assignment_id' => 52,
                'curricula_program_id' => 4,
                'semester_id' => 18,
                'course_id' => 48,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
