<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoursesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('courses')->insert([
            [
                'course_id' => 1,
                'course_code' => 'IT101',
                'course_title' => 'Introduction to Information Technology',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 2,
                'course_code' => 'IT102',
                'course_title' => 'Intermediate Information Technology',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 3,
                'course_code' => 'IT103',
                'course_title' => 'Advanced Information Technology',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 4,
                'course_code' => 'IT201',
                'course_title' => 'Information Systems',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 5,
                'course_code' => 'IT202',
                'course_title' => 'Data Structures',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 6,
                'course_code' => 'IT203',
                'course_title' => 'Algorithms',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 7,
                'course_code' => 'IT301',
                'course_title' => 'Database Management',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 8,
                'course_code' => 'IT302',
                'course_title' => 'Network Security',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 9,
                'course_code' => 'IT303',
                'course_title' => 'Software Engineering',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 10,
                'course_code' => 'COMP101',
                'course_title' => 'Intro to Computing',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 11,
                'course_code' => 'COMP102',
                'course_title' => 'Programming Fundamentals',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 12,
                'course_code' => 'COMP103',
                'course_title' => 'Computer Architecture',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 13,
                'course_code' => 'COMP201',
                'course_title' => 'Object-Oriented Programming',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 14,
                'course_code' => 'COMP202',
                'course_title' => 'Web Development',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 15,
                'course_code' => 'COMP203',
                'course_title' => 'Mobile Application Development',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 16,
                'course_code' => 'COMP301',
                'course_title' => 'Advanced Programming',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 17,
                'course_code' => 'COMP302',
                'course_title' => 'Software Testing',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 18,
                'course_code' => 'COMP303',
                'course_title' => 'Cloud Computing',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 19,
                'course_code' => 'ENG101',
                'course_title' => 'Engineering Mechanics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 20,
                'course_code' => 'ENG102',
                'course_title' => 'Thermodynamics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 21,
                'course_code' => 'ENG103',
                'course_title' => 'Material Science',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 22,
                'course_code' => 'ENG201',
                'course_title' => 'Fluid Mechanics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 23,
                'course_code' => 'ENG202',
                'course_title' => 'Machine Design',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 24,
                'course_code' => 'ENG203',
                'course_title' => 'Manufacturing Processes',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 25,
                'course_code' => 'ENG301',
                'course_title' => 'Robotics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 26,
                'course_code' => 'ENG302',
                'course_title' => 'Automated Systems',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 27,
                'course_code' => 'ENG303',
                'course_title' => 'Control Systems',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 28,
                'course_code' => 'ME101',
                'course_title' => 'Introduction to Mechanical Engineering',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 29,
                'course_code' => 'ME102',
                'course_title' => 'Engineering Drawing',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 30,
                'course_code' => 'ME103',
                'course_title' => 'Dynamics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 31,
                'course_code' => 'ME201',
                'course_title' => 'Thermodynamics II',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 32,
                'course_code' => 'ME202',
                'course_title' => 'Heat Transfer',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 33,
                'course_code' => 'ME203',
                'course_title' => 'Machine Elements',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 34,
                'course_code' => 'ME301',
                'course_title' => 'Mechatronics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 35,
                'course_code' => 'ME302',
                'course_title' => 'Advanced Manufacturing',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 36,
                'course_code' => 'ME303',
                'course_title' => 'Finite Element Analysis',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 37,
                'course_code' => 'IT104',
                'course_title' => 'Operating Systems',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 38,
                'course_code' => 'IT105',
                'course_title' => 'Computer Networks',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 39,
                'course_code' => 'IT106',
                'course_title' => 'Software Development',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 40,
                'course_code' => 'COMP104',
                'course_title' => 'Data Analytics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 41,
                'course_code' => 'COMP105',
                'course_title' => 'Cybersecurity Fundamentals',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 42,
                'course_code' => 'COMP106',
                'course_title' => 'Artificial Intelligence',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 43,
                'course_code' => 'ENG104',
                'course_title' => 'Solid Mechanics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 44,
                'course_code' => 'ENG105',
                'course_title' => 'Thermal Systems',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 45,
                'course_code' => 'ENG106',
                'course_title' => 'Manufacturing Automation',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 46,
                'course_code' => 'ME104',
                'course_title' => 'Vibrations',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 47,
                'course_code' => 'ME105',
                'course_title' => 'Fluid Dynamics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'course_id' => 48,
                'course_code' => 'ME106',
                'course_title' => 'Advanced Robotics',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 4,
                'tuition_hours' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
