<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CoursesTableSeeder extends Seeder
{
    public function run()
    {{
        $currentTimestamp = Carbon::now();

// Inserting data into courses
        DB::table('courses')->insert([
            [
                'course_id' => 1,
                'semester_id' => 1,
                'course_code' => 'CS101',
                'course_title' => 'Introduction to Programming',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 2,
                'semester_id' => 1,
                'course_code' => 'IT101',
                'course_title' => 'Information Technology Fundamentals',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 3,
                'semester_id' => 2,
                'course_code' => 'CS102',
                'course_title' => 'Data Structures',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 4,
                'semester_id' => 2,
                'course_code' => 'IT102',
                'course_title' => 'Networking Fundamentals',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 5,
                'semester_id' => 3,
                'course_code' => 'CS103',
                'course_title' => 'Object-Oriented Programming',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 6,
                'semester_id' => 4,
                'course_code' => 'CS201',
                'course_title' => 'Database Systems',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 7,
                'semester_id' => 4,
                'course_code' => 'IT201',
                'course_title' => 'Web Development',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 8,
                'semester_id' => 5,
                'course_code' => 'CS202',
                'course_title' => 'Algorithms',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 9,
                'semester_id' => 5,
                'course_code' => 'IT202',
                'course_title' => 'System Analysis and Design',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 10,
                'semester_id' => 6,
                'course_code' => 'CS203',
                'course_title' => 'Software Engineering',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 11,
                'semester_id' => 7,
                'course_code' => 'CS301',
                'course_title' => 'Operating Systems',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 12,
                'semester_id' => 7,
                'course_code' => 'IT301',
                'course_title' => 'Mobile Application Development',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 13,
                'semester_id' => 8,
                'course_code' => 'CS302',
                'course_title' => 'Artificial Intelligence',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 14,
                'semester_id' => 8,
                'course_code' => 'IT302',
                'course_title' => 'Cloud Computing',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 15,
                'semester_id' => 9,
                'course_code' => 'CS303',
                'course_title' => 'Network Security',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 16,
                'semester_id' => 10,
                'course_code' => 'CS401',
                'course_title' => 'Capstone Project I',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 17,
                'semester_id' => 10,
                'course_code' => 'IT401',
                'course_title' => 'IT Elective I',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 18,
                'semester_id' => 11,
                'course_code' => 'CS402',
                'course_title' => 'Capstone Project II',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 19,
                'semester_id' => 11,
                'course_code' => 'IT402',
                'course_title' => 'IT Elective II',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 20,
                'semester_id' => 12,
                'course_code' => 'CS403',
                'course_title' => 'Internship',
                'lec_hours' => 0,
                'lab_hours' => 10,
                'units' => 10,
                'tuition_hours' => 10,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 21,
                'semester_id' => 13,
                'course_code' => 'ACC101',
                'course_title' => 'Introduction to Accounting',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 22,
                'semester_id' => 13,
                'course_code' => 'MATH101',
                'course_title' => 'Business Mathematics',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 23,
                'semester_id' => 14,
                'course_code' => 'ACC102',
                'course_title' => 'Financial Accounting',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 24,
                'semester_id' => 14,
                'course_code' => 'LAW101',
                'course_title' => 'Business Law',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 25,
                'semester_id' => 15,
                'course_code' => 'ACC103',
                'course_title' => 'Managerial Accounting',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 26,
                'semester_id' => 16,
                'course_code' => 'ACC201',
                'course_title' => 'Intermediate Accounting I',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 27,
                'semester_id' => 16,
                'course_code' => 'MATH201',
                'course_title' => 'Statistics',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 28,
                'semester_id' => 17,
                'course_code' => 'ACC202',
                'course_title' => 'Intermediate Accounting II',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 29,
                'semester_id' => 17,
                'course_code' => 'LAW201',
                'course_title' => 'Taxation',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 30,
                'semester_id' => 18,
                'course_code' => 'ACC203',
                'course_title' => 'Cost Accounting',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 31,
                'semester_id' => 19,
                'course_code' => 'ACC301',
                'course_title' => 'Advanced Accounting',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 32,
                'semester_id' => 19,
                'course_code' => 'LAW301',
                'course_title' => 'Advanced Taxation',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 33,
                'semester_id' => 20,
                'course_code' => 'ACC302',
                'course_title' => 'Auditing I',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 34,
                'semester_id' => 20,
                'course_code' => 'MATH301',
                'course_title' => 'Quantitative Techniques',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 35,
                'semester_id' => 21,
                'course_code' => 'ACC303',
                'course_title' => 'Auditing II',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 36,
                'semester_id' => 22,
                'course_code' => 'ACC401',
                'course_title' => 'Capstone Project I',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 37,
                'semester_id' => 22,
                'course_code' => 'ACC402',
                'course_title' => 'Accounting Elective I',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 38,
                'semester_id' => 23,
                'course_code' => 'ACC403',
                'course_title' => 'Capstone Project II',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 39,
                'semester_id' => 23,
                'course_code' => 'ACC404',
                'course_title' => 'Accounting Elective II',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 40,
                'semester_id' => 24,
                'course_code' => 'ACC405',
                'course_title' => 'Internship',
                'lec_hours' => 0,
                'lab_hours' => 10,
                'units' => 10,
                'tuition_hours' => 10,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 41,
                'semester_id' => 25,
                'course_code' => 'CS101',
                'course_title' => 'Introduction to Programming',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 42,
                'semester_id' => 25,
                'course_code' => 'IT101',
                'course_title' => 'Information Technology Fundamentals',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 43,
                'semester_id' => 26,
                'course_code' => 'CS104',
                'course_title' => 'Data Structures and Algorithms',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 44,
                'semester_id' => 26,
                'course_code' => 'IT102',
                'course_title' => 'Networking Fundamentals',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 45,
                'semester_id' => 27,
                'course_code' => 'CS105',
                'course_title' => 'Advanced Programming',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 46,
                'semester_id' => 28,
                'course_code' => 'CS204',
                'course_title' => 'Database Systems and Applications',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 47,
                'semester_id' => 28,
                'course_code' => 'IT201',
                'course_title' => 'Web and Mobile Development',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 48,
                'semester_id' => 29,
                'course_code' => 'CS205',
                'course_title' => 'Advanced Algorithms',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 49,
                'semester_id' => 29,
                'course_code' => 'IT203',
                'course_title' => 'Advanced Networking',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 50,
                'semester_id' => 30,
                'course_code' => 'CS206',
                'course_title' => 'Software Engineering Principles',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 51,
                'semester_id' => 31,
                'course_code' => 'CS307',
                'course_title' => 'Operating Systems and Virtualization',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 52,
                'semester_id' => 31,
                'course_code' => 'IT301',
                'course_title' => 'Advanced Mobile Development',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 53,
                'semester_id' => 32,
                'course_code' => 'CS308',
                'course_title' => 'Machine Learning',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 54,
                'semester_id' => 32,
                'course_code' => 'IT302',
                'course_title' => 'Cloud Services and Infrastructure',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 55,
                'semester_id' => 33,
                'course_code' => 'CS309',
                'course_title' => 'Cybersecurity Essentials',
                'lec_hours' => 3,
                'lab_hours' => 2,
                'units' => 4,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 56,
                'semester_id' => 34,
                'course_code' => 'CS410',
                'course_title' => 'Capstone Project I',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 57,
                'semester_id' => 34,
                'course_code' => 'IT410',
                'course_title' => 'IT Elective I',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 58,
                'semester_id' => 35,
                'course_code' => 'CS411',
                'course_title' => 'Capstone Project II',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 59,
                'semester_id' => 35,
                'course_code' => 'IT411',
                'course_title' => 'IT Elective II',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 60,
                'semester_id' => 36,
                'course_code' => 'CS412',
                'course_title' => 'Internship',
                'lec_hours' => 0,
                'lab_hours' => 10,
                'units' => 10,
                'tuition_hours' => 10,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 61,
                'semester_id' => 37,
                'course_code' => 'ACC101',
                'course_title' => 'Introduction to Accounting',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 62,
                'semester_id' => 37,
                'course_code' => 'MATH102',
                'course_title' => 'Business Mathematics with Analytics',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 63,
                'semester_id' => 38,
                'course_code' => 'ACC104',
                'course_title' => 'Financial Reporting',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 64,
                'semester_id' => 38,
                'course_code' => 'LAW102',
                'course_title' => 'Business Law and Ethics',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 65,
                'semester_id' => 39,
                'course_code' => 'ACC105',
                'course_title' => 'Managerial Accounting and Control',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 66,
                'semester_id' => 40,
                'course_code' => 'ACC206',
                'course_title' => 'Intermediate Accounting I',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 67,
                'semester_id' => 40,
                'course_code' => 'MATH202',
                'course_title' => 'Statistics and Analytics',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 68,
                'semester_id' => 41,
                'course_code' => 'ACC207',
                'course_title' => 'Intermediate Accounting II',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 69,
                'semester_id' => 41,
                'course_code' => 'LAW202',
                'course_title' => 'Taxation and Compliance',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 70,
                'semester_id' => 42,
                'course_code' => 'ACC208',
                'course_title' => 'Cost and Management Accounting',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 71,
                'semester_id' => 43,
                'course_code' => 'ACC309',
                'course_title' => 'Advanced Financial Accounting',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 72,
                'semester_id' => 43,
                'course_code' => 'LAW303',
                'course_title' => 'Corporate Taxation',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 73,
                'semester_id' => 44,
                'course_code' => 'ACC310',
                'course_title' => 'Auditing Theory and Practice',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 74,
                'semester_id' => 44,
                'course_code' => 'MATH303',
                'course_title' => 'Quantitative Methods',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 75,
                'semester_id' => 45,
                'course_code' => 'ACC311',
                'course_title' => 'Advanced Auditing',
                'lec_hours' => 3,
                'lab_hours' => 1,
                'units' => 3,
                'tuition_hours' => 4,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 76,
                'semester_id' => 46,
                'course_code' => 'ACC412',
                'course_title' => 'Capstone Project I',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 77,
                'semester_id' => 46,
                'course_code' => 'ACC413',
                'course_title' => 'Accounting Elective I',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 78,
                'semester_id' => 47,
                'course_code' => 'ACC414',
                'course_title' => 'Capstone Project II',
                'lec_hours' => 1,
                'lab_hours' => 4,
                'units' => 3,
                'tuition_hours' => 5,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 79,
                'semester_id' => 47,
                'course_code' => 'ACC415',
                'course_title' => 'Accounting Elective II',
                'lec_hours' => 3,
                'lab_hours' => 0,
                'units' => 3,
                'tuition_hours' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'course_id' => 80,
                'semester_id' => 48,
                'course_code' => 'ACC416',
                'course_title' => 'Internship',
                'lec_hours' => 0,
                'lab_hours' => 10,
                'units' => 10,
                'tuition_hours' => 10,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
        ]);

        
    }}
}
