<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SchedulesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('schedules')->insert([
            [
                'schedule_id' => 1,
                'section_course_id' => 1,
                'day' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 1,
                'room_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 2,
                'section_course_id' => 2,
                'day' => 'Wednesday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 2,
                'room_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 3,
                'section_course_id' => 3,
                'day' => 'Friday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 3,
                'room_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 4,
                'section_course_id' => 4,
                'day' => 'Tuesday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 1,
                'room_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 5,
                'section_course_id' => 5,
                'day' => 'Thursday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 2,
                'room_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 6,
                'section_course_id' => 6,
                'day' => 'Monday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 3,
                'room_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 7,
                'section_course_id' => 7,
                'day' => 'Wednesday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 1,
                'room_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 8,
                'section_course_id' => 8,
                'day' => 'Friday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 2,
                'room_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 9,
                'section_course_id' => 9,
                'day' => 'Tuesday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 3,
                'room_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 10,
                'section_course_id' => 10,
                'day' => 'Thursday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 2,
                'room_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 11,
                'section_course_id' => 11,
                'day' => 'Monday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 3,
                'room_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 12,
                'section_course_id' => 12,
                'day' => 'Wednesday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 4,
                'room_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 13,
                'section_course_id' => 13,
                'day' => 'Friday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 2,
                'room_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 14,
                'section_course_id' => 14,
                'day' => 'Tuesday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 3,
                'room_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 15,
                'section_course_id' => 15,
                'day' => 'Thursday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 4,
                'room_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 16,
                'section_course_id' => 16,
                'day' => 'Monday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 2,
                'room_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 17,
                'section_course_id' => 17,
                'day' => 'Wednesday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 3,
                'room_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 18,
                'section_course_id' => 18,
                'day' => 'Friday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 4,
                'room_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 19,
                'section_course_id' => 19,
                'day' => 'Tuesday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 2,
                'room_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 20,
                'section_course_id' => 20,
                'day' => 'Thursday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 3,
                'room_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 21,
                'section_course_id' => 21,
                'day' => 'Monday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 4,
                'room_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 22,
                'section_course_id' => 22,
                'day' => 'Wednesday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 2,
                'room_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 23,
                'section_course_id' => 23,
                'day' => 'Friday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 3,
                'room_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 24,
                'section_course_id' => 24,
                'day' => 'Tuesday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 4,
                'room_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 25,
                'section_course_id' => 25,
                'day' => 'Thursday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 2,
                'room_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 26,
                'section_course_id' => 26,
                'day' => 'Monday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 3,
                'room_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 27,
                'section_course_id' => 27,
                'day' => 'Wednesday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 4,
                'room_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 28,
                'section_course_id' => 28,
                'day' => 'Friday',
                'start_time' => '09:00:00',
                'end_time' => '10:30:00',
                'faculty_id' => 2,
                'room_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 29,
                'section_course_id' => 29,
                'day' => 'Tuesday',
                'start_time' => '11:00:00',
                'end_time' => '12:30:00',
                'faculty_id' => 3,
                'room_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'schedule_id' => 30,
                'section_course_id' => 30,
                'day' => 'Thursday',
                'start_time' => '14:00:00',
                'end_time' => '15:30:00',
                'faculty_id' => 4,
                'room_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
