<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SemestersTableSeeder extends Seeder
{
    public function run()
    {{
        $currentTimestamp = Carbon::now();

// Inserting data into semesters
        DB::table('semesters')->insert([
            [
                'semester_id' => 1,
                'year_level_id' => 1,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 2,
                'year_level_id' => 1,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 3,
                'year_level_id' => 1,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 4,
                'year_level_id' => 2,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 5,
                'year_level_id' => 2,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 6,
                'year_level_id' => 2,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 7,
                'year_level_id' => 3,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 8,
                'year_level_id' => 3,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 9,
                'year_level_id' => 3,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 10,
                'year_level_id' => 4,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 11,
                'year_level_id' => 4,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 12,
                'year_level_id' => 4,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 13,
                'year_level_id' => 5,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 14,
                'year_level_id' => 5,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 15,
                'year_level_id' => 5,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 16,
                'year_level_id' => 6,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 17,
                'year_level_id' => 6,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 18,
                'year_level_id' => 6,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 19,
                'year_level_id' => 7,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 20,
                'year_level_id' => 7,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 21,
                'year_level_id' => 7,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 22,
                'year_level_id' => 8,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 23,
                'year_level_id' => 8,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 24,
                'year_level_id' => 8,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 25,
                'year_level_id' => 9,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 26,
                'year_level_id' => 9,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 27,
                'year_level_id' => 9,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 28,
                'year_level_id' => 10,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 29,
                'year_level_id' => 10,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 30,
                'year_level_id' => 10,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 31,
                'year_level_id' => 11,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 32,
                'year_level_id' => 11,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 33,
                'year_level_id' => 11,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 34,
                'year_level_id' => 12,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 35,
                'year_level_id' => 12,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 36,
                'year_level_id' => 12,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 37,
                'year_level_id' => 13,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 38,
                'year_level_id' => 13,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 39,
                'year_level_id' => 13,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 40,
                'year_level_id' => 14,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 41,
                'year_level_id' => 14,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 42,
                'year_level_id' => 14,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 43,
                'year_level_id' => 15,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 44,
                'year_level_id' => 15,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 45,
                'year_level_id' => 15,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 46,
                'year_level_id' => 16,
                'semester' => 1,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 47,
                'year_level_id' => 16,
                'semester' => 2,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
            [
                'semester_id' => 48,
                'year_level_id' => 16,
                'semester' => 3,
                'created_at' => $currentTimestamp,
                'updated_at' => $currentTimestamp,
            ],
        ]);

        
    }}
}
